name: 06- Contexts
run-name: 06- Contexts |DEBUG - ${{ inputs.debug }}
on:
    push:
    workflow_dispatch:
        inputs: 
            debug:
                type: boolean
                default: false
env:
    MY_WORKFLOW_VAR: 'workflow'
    MY_OVERWRIITEN_VAR: 'workflow'

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: 'job'
            MY_OVERWRITTEN_VAR: 'job'

        steps: 
            - name: Display Information
              run: |
                echo "Event Name: ${{ github.event_name }}"
                echo "Ref: ${{ github.Ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Worflow: ${{github.workflow }}"
                echo "RUN ID: ${{github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"
            - name: Retreive Variable
              run: |
                echo "Variable value ${{ vars.MY_VAR }}"
            - name: Print Env Variables
              env:
                 MY_OVERWRIITEN_VAR: 'step'
              run: |
                echo "Workflow Env : ${{ env.MY_WORKFLOW_VAR}}"
                echo "Workflow Env : ${{ env.MY_OVERWRIITEN_VAR}}"
            
            - name: Print Env Variables
              run: |
                echo "Workflow Env : ${{ env.MY_WORKFLOW_VAR}}"
                echo "Workflow Env : ${{ env.MY_OVERWRIITEN_VAR}}"


