name: 13- Using Caching in workflow

on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: Wheteher to execute cache step
                type: boolean
                default: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Testing
              run: npm run test
              working-directory: 13-caching/react-app
            - name: Building
              run: npm run build
              working-directory: 13-caching/react-app
            - name: Deploy to Non Prod
              run: echo "Deploying to non-prod"
              working-directory: 13-caching/react-app
